/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

package org.opensearch.timeseries.util;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.opensearch.action.DocWriteRequest;
import org.opensearch.action.bulk.BulkItemResponse;
import org.opensearch.action.bulk.BulkRequest;
import org.opensearch.action.bulk.BulkResponse;
import org.opensearch.action.index.IndexRequest;
import org.opensearch.core.rest.RestStatus;

public class BulkUtil {
    private static final Logger logger = LogManager.getLogger(BulkUtil.class);

    public static List<IndexRequest> getFailedIndexRequest(BulkRequest bulkRequest, BulkResponse bulkResponse) {
        return getFailedIndexRequests(bulkRequest, bulkResponse, response -> ExceptionUtil.isRetryAble(response.getFailure().getStatus()));
    }

    public static List<IndexRequest> getMissingResultIndexRequests(BulkRequest bulkRequest, BulkResponse bulkResponse) {
        return getFailedIndexRequests(bulkRequest, bulkResponse, BulkUtil::isIndexNotFoundFailure);
    }

    private static boolean isIndexNotFoundFailure(BulkItemResponse response) {
        BulkItemResponse.Failure failure = response.getFailure();
        String failureMessage = response.getFailureMessage();
        return failure != null
            && (failure.getStatus() == RestStatus.NOT_FOUND
                || ExceptionUtil.isIndexNotFoundInMessage(failure.getCause())
                || (failureMessage != null && failureMessage.contains("index_not_found_exception")));
    }

    private static List<IndexRequest> getFailedIndexRequests(
        BulkRequest bulkRequest,
        BulkResponse bulkResponse,
        Predicate<BulkItemResponse> shouldInclude
    ) {
        List<IndexRequest> res = new ArrayList<>();

        if (bulkResponse == null || bulkRequest == null) {
            return res;
        }

        List<DocWriteRequest<?>> requests = bulkRequest.requests();
        for (BulkItemResponse response : bulkResponse.getItems()) {
            if (response.isFailed()) {
                logger.info("bulk indexing failure: {}", response.getFailureMessage());
                if (shouldInclude.test(response)) {
                    int itemId = response.getItemId();
                    if (itemId >= 0 && itemId < requests.size()) {
                        DocWriteRequest<?> request = requests.get(itemId);
                        try {
                            res.add((IndexRequest) request);
                        } catch (ClassCastException e) {
                            logger.error("We only support IndexRequest");
                            throw e;
                        }
                    } else {
                        logger.warn("Failed bulk item id [{}] is out of range for request size [{}]", itemId, requests.size());
                    }
                }
            }
        }
        return res;
    }

    /**
     * Copy original request's source without other information like autoGeneratedTimestamp.
     * otherwise, an exception will be thrown indicating autoGeneratedTimestamp should not be set
     * while request id is already set (id is set because we have already sent the request before).
     * @param indexRequest request to be cloned
     * @return cloned Request
     */
    public static IndexRequest cloneIndexRequest(IndexRequest indexRequest) {
        IndexRequest newRequest = new IndexRequest(indexRequest.index());
        newRequest.source(indexRequest.source(), indexRequest.getContentType());
        return newRequest;
    }
}
